/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package koneksi.ke.java;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author tosiba
 */
public class obat extends javax.swing.JFrame {

    /**
     * Creates new form obat
     */
    static Connection conn;
    static Statement stmt;
    static ResultSet rs;
    public obat() {
        initComponents();
        setobat();
    }
    public void setobat(){
        String sql = "SELECT * FROM obat";
            Connection conn = null;
            try{
                conn = DriverManager.getConnection("jdbc:mysql://localhost/klinik", "root", "");
            } catch(SQLException e){
                System.out.println("error");
            }
            try{
            Statement pstmt = conn.createStatement();
            ResultSet rs = pstmt.executeQuery(sql);
            //while(rs.next()) System.out.println(rs.getString("nama_pasien"));
            tabelobat.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
            System.out.println(e.getMessage());
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelobat = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nama_obat = new javax.swing.JTextField();
        kadal = new javax.swing.JTextField();
        stock = new javax.swing.JTextField();
        fungsi = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        cari_obat = new javax.swing.JLabel();
        daftar_obat = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        daftarpasien = new javax.swing.JMenuItem();
        home = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tabelobat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelobat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelobatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelobat);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 600, 1260, 140);

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fungsi");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(470, 490, 180, 44);

        nama_obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_obatActionPerformed(evt);
            }
        });
        getContentPane().add(nama_obat);
        nama_obat.setBounds(720, 270, 130, 30);
        getContentPane().add(kadal);
        kadal.setBounds(720, 320, 130, 30);
        getContentPane().add(stock);
        stock.setBounds(720, 390, 130, 30);
        getContentPane().add(fungsi);
        fungsi.setBounds(720, 510, 130, 30);
        getContentPane().add(id);
        id.setBounds(720, 210, 130, 30);
        getContentPane().add(harga);
        harga.setBounds(720, 460, 130, 30);

        cari_obat.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        cari_obat.setText("Update");
        cari_obat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cari_obatMouseClicked(evt);
            }
        });
        getContentPane().add(cari_obat);
        cari_obat.setBounds(800, 550, 90, 30);

        daftar_obat.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        daftar_obat.setText("Daftar");
        daftar_obat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftar_obatMouseClicked(evt);
            }
        });
        getContentPane().add(daftar_obat);
        daftar_obat.setBounds(490, 550, 80, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\tosiba\\Desktop\\Files\\Tubes PBO\\obat3.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1366, 750);

        jMenu4.setText("Go To");

        daftarpasien.setText("Daftar Pasien Lama");
        daftarpasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarpasienActionPerformed(evt);
            }
        });
        jMenu4.add(daftarpasien);

        home.setText("Halaman Utama");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jMenu4.add(home);

        jMenuBar2.add(jMenu4);
        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void daftarpasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarpasienActionPerformed
        // TODO add your handling code here:
        dispose();
        pasienlama pl=new pasienlama();
        pl.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_daftarpasienActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        dispose();
        view utama=new view();
        utama.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_homeActionPerformed

    private void cari_obatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cari_obatMouseClicked
        // TODO add your handling code here:
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Untuk Update Record ini???","Confirmation",JOptionPane.YES_NO_OPTION);
        if(ok==0){
            KoneksiKeJava koneksi = new KoneksiKeJava();
            koneksi.updateobat(id.getText(), nama_obat.getText(),kadal.getText(), Integer.parseInt(stock.getText()), fungsi.getText(), Integer.parseInt(harga.getText()));
            JOptionPane.showMessageDialog(null, "Update Berhasil");
            setobat();
        }else{
            //Nothing
        }
    }//GEN-LAST:event_cari_obatMouseClicked

    private void daftar_obatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftar_obatMouseClicked
        // TODO add your handling code here:
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Untuk Update Record ini???","Confirmation",JOptionPane.YES_NO_OPTION);
        if(ok==0){
            KoneksiKeJava konek=new KoneksiKeJava();
            konek.tambahobat(id.getText(), nama_obat.getText(),kadal.getText(), Integer.parseInt(stock.getText()), fungsi.getText(), Integer.parseInt(harga.getText()));
            JOptionPane.showMessageDialog(null, "Tambah Pasien Berhasiel");
        }
        else {
            //nothing
        }
    }//GEN-LAST:event_daftar_obatMouseClicked

    private void nama_obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_obatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_obatActionPerformed

    private void tabelobatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelobatMouseClicked
        // TODO add your handling code here:
       // id.getText(), nama_obat.getText(),kadal.getText(), Integer.parseInt(stock.getText()), fungsi.getText(), Integer.parseInt(harga.getText()
        DefaultTableModel model = (DefaultTableModel)tabelobat.getModel();
        int selectedRowIndex = tabelobat.getSelectedRow();
        id.setText(model.getValueAt(selectedRowIndex, 1).toString());
        kadal.setText(model.getValueAt(selectedRowIndex, 3).toString());
        nama_obat.setText(model.getValueAt(selectedRowIndex, 2).toString());
        stock.setText(model.getValueAt(selectedRowIndex, 4).toString());
        fungsi.setText(model.getValueAt(selectedRowIndex, 5).toString());
        harga.setText(model.getValueAt(selectedRowIndex, 6).toString());
    }//GEN-LAST:event_tabelobatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new obat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cari_obat;
    private javax.swing.JLabel daftar_obat;
    private javax.swing.JMenuItem daftarpasien;
    private javax.swing.JTextField fungsi;
    private javax.swing.JTextField harga;
    private javax.swing.JMenuItem home;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kadal;
    private javax.swing.JTextField nama_obat;
    private javax.swing.JTextField stock;
    private javax.swing.JTable tabelobat;
    // End of variables declaration//GEN-END:variables
}
