package koneksi.ke.java;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static koneksi.ke.java.KoneksiKeJava.DB_URL;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tosiba
 */
public class pasienlama extends javax.swing.JFrame {
    static Connection conn;
    static Statement stmt;
    static ResultSet rs;
    /**
     * Creates new form pasienlama
     */
    public pasienlama() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        settab();
       
        
    }
    
    public void settab(){
        String sql = "SELECT * FROM pasien";
            conn = null;
            try{
                conn = DriverManager.getConnection("jdbc:mysql://localhost/klinik", "root", "");
            } catch(SQLException e){
                System.out.println("error");
            }
            try{
            stmt = conn.createStatement();
            rs = stmt.executeQuery(sql);
            //while(rs.next()) System.out.println(rs.getString("nama_pasien"));
            jTable3.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
            System.out.println(e.getMessage());
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        nama_pasien = new javax.swing.JTextField();
        berat_badan = new javax.swing.JTextField();
        tinggi_badan = new javax.swing.JTextField();
        gol_darah = new javax.swing.JTextField();
        riwayat_penyakit = new javax.swing.JTextField();
        umur = new javax.swing.JTextField();
        alergi = new javax.swing.JTextField();
        update_yoeeh = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(100, 590, 1130, 138);
        getContentPane().add(nama_pasien);
        nama_pasien.setBounds(500, 160, 130, 40);
        getContentPane().add(berat_badan);
        berat_badan.setBounds(800, 280, 130, 40);

        tinggi_badan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggi_badanActionPerformed(evt);
            }
        });
        getContentPane().add(tinggi_badan);
        tinggi_badan.setBounds(800, 160, 130, 40);

        gol_darah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gol_darahActionPerformed(evt);
            }
        });
        getContentPane().add(gol_darah);
        gol_darah.setBounds(500, 310, 130, 40);

        riwayat_penyakit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riwayat_penyakitActionPerformed(evt);
            }
        });
        getContentPane().add(riwayat_penyakit);
        riwayat_penyakit.setBounds(800, 400, 130, 40);
        getContentPane().add(umur);
        umur.setBounds(500, 230, 130, 40);

        alergi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alergiActionPerformed(evt);
            }
        });
        getContentPane().add(alergi);
        alergi.setBounds(500, 390, 130, 40);

        update_yoeeh.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        update_yoeeh.setForeground(new java.awt.Color(255, 255, 255));
        update_yoeeh.setText("Update");
        update_yoeeh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_yoeehMouseClicked(evt);
            }
        });
        getContentPane().add(update_yoeeh);
        update_yoeeh.setBounds(990, 520, 102, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\tosiba\\Desktop\\Files\\Tubes PBO\\pasienlama1.jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 1370, 760);

        jMenu4.setText("Go To");

        jMenuItem2.setText("Halaman Utama");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("Daftar Obat");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar2.add(jMenu4);
        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tinggi_badanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggi_badanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggi_badanActionPerformed

    private void gol_darahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gol_darahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gol_darahActionPerformed

    private void riwayat_penyakitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riwayat_penyakitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_riwayat_penyakitActionPerformed

    private void alergiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alergiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alergiActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable3.getModel();
        int selectedRowIndex = jTable3.getSelectedRow();
        nama_pasien.setText(model.getValueAt(selectedRowIndex, 1).toString());
        tinggi_badan.setText(model.getValueAt(selectedRowIndex, 3).toString());
        berat_badan.setText(model.getValueAt(selectedRowIndex, 2).toString());
        riwayat_penyakit.setText(model.getValueAt(selectedRowIndex, 4).toString());
        gol_darah.setText(model.getValueAt(selectedRowIndex, 5).toString());
        umur.setText(model.getValueAt(selectedRowIndex, 6).toString());
        alergi.setText(model.getValueAt(selectedRowIndex, 7).toString());
    }//GEN-LAST:event_jTable3MouseClicked

    private void update_yoeehMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_yoeehMouseClicked
        // TODO add your handling code here:
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Untuk Update Record ini???","Confirmation",JOptionPane.YES_NO_OPTION);
        if(ok==0){
            KoneksiKeJava koneksi = new KoneksiKeJava();
            koneksi.updatedata(nama_pasien.getText(), gol_darah.getText(), berat_badan.getText(), tinggi_badan.getText(), riwayat_penyakit.getText(), alergi.getText(), Integer.parseInt(umur.getText()));
            JOptionPane.showMessageDialog(null, "Update Berhasil");
            settab();
        }else{
            //Nothing
        }
    }//GEN-LAST:event_update_yoeehMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        dispose();
        view ok=new view();
        ok.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        dispose();
        obat ia=new obat();
        ia.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pasienlama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pasienlama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pasienlama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pasienlama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pasienlama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alergi;
    private javax.swing.JTextField berat_badan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JTextField gol_darah;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField nama_pasien;
    private javax.swing.JTextField riwayat_penyakit;
    private javax.swing.JTextField tinggi_badan;
    private javax.swing.JTextField umur;
    private javax.swing.JLabel update_yoeeh;
    // End of variables declaration//GEN-END:variables
}
