package koneksi.ke.java;


import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tosiba
 */
public class view extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    
    public view() {
        initComponents();
    }
    
    public void showberhasil(){
        JOptionPane.showMessageDialog(this, "Berhasil Mendaftarkan Dokter", "Berhasil Daftar", WIDTH);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        idDokter = new javax.swing.JTextField();
        namaDokter = new javax.swing.JTextField();
        daftar_pasien_baru = new javax.swing.JLabel();
        edit_pasien_lama = new javax.swing.JLabel();
        daftar_dokter = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);

        idDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idDokterActionPerformed(evt);
            }
        });
        getContentPane().add(idDokter);
        idDokter.setBounds(580, 170, 310, 30);

        namaDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaDokterActionPerformed(evt);
            }
        });
        getContentPane().add(namaDokter);
        namaDokter.setBounds(580, 220, 310, 30);

        daftar_pasien_baru.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        daftar_pasien_baru.setText("    Daftar");
        daftar_pasien_baru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftar_pasien_baruMouseClicked(evt);
            }
        });
        getContentPane().add(daftar_pasien_baru);
        daftar_pasien_baru.setBounds(840, 480, 140, 40);

        edit_pasien_lama.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        edit_pasien_lama.setText("    Daftar");
        edit_pasien_lama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_pasien_lamaMouseClicked(evt);
            }
        });
        getContentPane().add(edit_pasien_lama);
        edit_pasien_lama.setBounds(490, 480, 140, 40);

        daftar_dokter.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        daftar_dokter.setText("Daftar");
        daftar_dokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftar_dokterMouseClicked(evt);
            }
        });
        getContentPane().add(daftar_dokter);
        daftar_dokter.setBounds(930, 190, 80, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\tosiba\\Desktop\\Files\\Tubes PBO\\view.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1370, 750);

        jMenu4.setText("Go To");

        jMenuItem3.setText("Daftar Obat");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar2.add(jMenu4);
        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idDokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idDokterActionPerformed

    private void namaDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaDokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaDokterActionPerformed

    private void daftar_pasien_baruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftar_pasien_baruMouseClicked
        // TODO add your handling code here:
        dispose();
        pasienbaru daftar_p= new pasienbaru();
        daftar_p.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_daftar_pasien_baruMouseClicked

    private void edit_pasien_lamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_pasien_lamaMouseClicked
        // TODO add your handling code here:
        dispose();
        pasienlama berubah=new pasienlama();
        berubah.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_edit_pasien_lamaMouseClicked

    private void daftar_dokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftar_dokterMouseClicked
        // TODO add your handling code here:
         KoneksiKeJava konek = new KoneksiKeJava();
         int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Untuk Update Record ini???","Confirmation",JOptionPane.YES_NO_OPTION);
        if(ok==0){
//        System.out.println(idDokter.getText() + namaDokter.getText());
        konek.daftarDokter(idDokter.getText(), namaDokter.getText() );
        }else{
  //nothing
        }
    }//GEN-LAST:event_daftar_dokterMouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        dispose();
        obat cie =new obat();
        cie.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel daftar_dokter;
    private javax.swing.JLabel daftar_pasien_baru;
    private javax.swing.JLabel edit_pasien_lama;
    private javax.swing.JTextField idDokter;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField namaDokter;
    // End of variables declaration//GEN-END:variables
}
